language: php

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/grumphp run
  - vendor/bin/phpunit tests --coverage-clover clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email:
    on_success: never
